"""Tests package for cocotbext-i2s."""
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, Timer
from cocotb.regression import TestFactory

from cocotbext.i2s.driver import I2sMaster, I2sSlave
from cocotbext.i2s.monitor import I2sMonitor

import random

# Helper task for generating the main system clock
async def clock_gen(signal):
    """System Clock Generator."""
    await cocotb.start(Clock(signal, 10, units="ns").start())

# Helper task for resetting the DUT
async def reset_dut(reset_signal, duration_ns):
    """Resets the DUT."""
    reset_signal.value = 1
    await Timer(duration_ns, units="ns")
    reset_signal.value = 0
    reset_signal._log.info("Reset complete")

# Main test function, parameterized to run multiple scenarios
async def run_test(dut, *, data_width=24, master_mode=True):
    """Main parameterized test function for I2S verification.

    Args:
        dut: The design under test.
        data_width (int): The width of the data words to be transmitted/received.
        master_mode (bool): True for DUT as Master, False for DUT as Slave.
    """
    # Start the system clock
    await clock_gen(dut.i_clk)

    # Reset the DUT
    await reset_dut(dut.i_rst, 20)

    # --- Test Data Generation ---
    # Generate 10 random 24-bit data words for left and right channels
    test_data_left = [random.getrandbits(data_width) for _ in range(10)]
    test_data_right = [random.getrandbits(data_width) for _ in range(10)]
    # We interleave them for transmission, similar to how I2S works
    interleaved_data = [val for pair in zip(test_data_left, test_data_right) for val in pair]

    # --- Verification Component Initialization ---
    if master_mode:
        dut._log.info("Configuring test for DUT as MASTER.")
        # DUT is Master, so testbench needs a Slave to receive data
        # The Slave driver listens to the clocks generated by the DUT
        i2s_peripheral = I2sSlave(
            dut,
            sclk=dut.o_bclk,
            ws=dut.o_wclk,
            sd=dut.o_sd,
            data_width=data_width,
        )
    else:
        dut._log.info("Configuring test for DUT as SLAVE.")
        # DUT is Slave, so testbench needs a Master to provide clocks and data
        i2s_peripheral = I2sMaster(
            dut,
            sclk=dut.i_bclk,
            ws=dut.i_wclk,
            sd=dut.i_sd,
            data_width=data_width,
        )

    # --- DUT Configuration ---
    dut.i_enable.value = 1
    dut.i_mode.value = 0 if master_mode else 1 # 0 for Master, 1 for Slave
    dut.G_NBITS.value = data_width

    # --- Test Execution ---
    await RisingEdge(dut.i_clk)

    if master_mode:
        # DUT is Master, we need to provide it with data to transmit
        for i in range(len(test_data_left)):
            # Load left channel data
            dut.i_data.value = test_data_left[i]
            dut.i_valid_data.value = 1
            await RisingEdge(dut.i_clk)
            dut.i_valid_data.value = 0

            # Wait for DUT to be ready for the next word
            # A more robust implementation might use a handshake signal
            await Timer(1, units="us")

            # Load right channel data
            dut.i_data.value = test_data_right[i]
            dut.i_valid_data.value = 1
            await RisingEdge(dut.i_clk)
            dut.i_valid_data.value = 0
            await Timer(1, units="us")

        # Now, receive the data using our I2S Slave driver
        received_data = []
        for _ in range(len(interleaved_data)):
            data_word = await i2s_peripheral.recv_word()
            received_data.append(data_word)

        dut._log.info(f"Original interleaved data: {interleaved_data}")
        dut._log.info(f"Data received by slave:    {received_data}")

        # --- Verification ---
        assert received_data == interleaved_data, "Mismatch between transmitted and received data"  # noqa: S101

    else: # Slave Mode
        # DUT is Slave, so our testbench Master sends data to it
        await i2s_peripheral.write(interleaved_data)

        # Wait for the DUT to process the data
        await Timer(10, units="us")

        # Read the received data from the monitor
        # The monitor would have captured the data that the DUT received and processed
        # For this DUT, we assume it loops back or makes data available somehow.
        # Since i2s_simple.vhd doesn't loop back slave input to a readable output,
        # we'll rely on waveform inspection for this part. A real DUT would have an output FIFO.
        # This highlights a limitation in the DUT, not the testbench.
        dut._log.warning("Slave receive check relies on waveform analysis as DUT has no output path for received data.")


    await Timer(50, units="us") # Wait for end of simulation
    dut._log.info("Test finished successfully.")


# --- Test Registration ---
# Use TestFactory to automatically generate tests from the run_test function
# This will create two test cases: one for master mode and one for slave mode.
factory = TestFactory(run_test)
factory.add_option("data_width", [24, 32]) # Test with 24 and 32 bit data
factory.add_option("master_mode", [True, False]) # Test both master and slave modes
factory.generate_tests()

